package com.sebone.deliveringsmiles.interfaceimpl;

import java.util.List;

import com.sebone.deliveringsmiles.dataobjects.OrderStatus;
import com.sebone.deliveringsmiles.dataobjects.PayoutData;
import com.sebone.deliveringsmiles.interfaces.Payout;


/*
 * This is the implementation of DriverRegistration interface, PayoutImpl is the class where we defined all the methods regarding payouts,
 * like what is the amount of the money the driver got from 
 * a particular order, what is the monthly payout generated by the driver and all the things.
 * 
 * @author Bhanu Singh
 * @date: 24/03/2022 
 */
public class PayoutImpl implements Payout{
	
	/*
	 * With the help of this method the user will get the total payout of a particular order.
	 * In this method we will fetch total payout with the help of order Id
	 * 
	 * @author Bhanu Singh
	 * @date 24/03/2022
	 * 
	 * @param orderId 
	 * @param driverId
	 * 
	 * @return payoutData 	object of class PayoutData
	 * 
	 */
	public PayoutData payoutByOrder(int orderId, int driverId) {
		return null;
	}
	
	
	/*
	 * With the help of this method the user will get the payout data according to the user input date or time.
	 * In this method date and time will be given by the user and payout will be generated .
	 * 
	 * @author Bhanu Singh
	 * @date 24/03/2022
	 * 
	 * @param orderStatus 	object of class OrderStatus 
	 * @param driverId
	 * @param startDate
	 * @param endDate
	 * 
	 * @return List<PayoutData> 	List of objects of class PayoutData
	 * 
	 */
	public List<PayoutData> payoutOfTheDays(OrderStatus orderStatus, int driverId , String startDate, String endDate) {
		return null;
	}
	
	/*
	 * With the help of this method the user will be able to generate total payout of his total successful deliverys.
	 * In this method we will show the total payout of the driverId will be fetched.
	 * 
	 * @author Bhanu Singh
	 * @date 24/03/2022
	 * 
	 * @param driverId
	 * 
	 * @return List<PayoutData> 	List of objects of class PayoutData
	 * 
	 */
	public List<PayoutData> totalPayout(int driverId) {
		return null;
	}
}
